export default function Terms() {
  return (
    <main className="policy-page">
      <h1>Terms and Conditions</h1>

      <p>
        Masari is a cloud-based personal finance application that enables users
        to track expenses, organize financial information, and receive insights.
        By accessing or using Masari, you agree to these Terms and Conditions.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 13 years old (or the minimum legal age in your
        jurisdiction) to use Masari.
      </p>

      <h2>2. Use of Service</h2>
      <p>You agree to:</p>
      <ul>
        <li>Use Masari only for lawful purposes</li>
        <li>Provide accurate information where applicable</li>
        <li>Not attempt to disrupt, reverse engineer, or misuse the service</li>
      </ul>

      <h2>3. Accounts</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account
        and for all activities that occur under your account.
      </p>

      <h2>4. Cloud-Based Service</h2>
      <p>
        Masari requires an internet connection to function. We do not guarantee
        uninterrupted availability, and outages or maintenance may temporarily
        affect access.
      </p>

      <h2>5. Your Data</h2>
      <p>
        You retain ownership of the financial and personal data you enter into
        Masari. By using the service, you grant us permission to process this
        data solely to provide and improve the application.
      </p>

      <h2>6. Financial Disclaimer</h2>
      <p>
        Masari is a budgeting and tracking tool only and does not provide
        financial, investment, tax, or legal advice. Any insights or
        recommendations generated by the app are informational and should not be
        relied upon as professional advice.
      </p>

      <h2>7. AI Features</h2>
      <p>
        Masari may provide AI-powered suggestions and automation. These outputs
        may be incomplete or inaccurate and are provided for convenience only.
        Users remain responsible for reviewing and verifying all financial
        information.
      </p>

      <h2>8. Subscriptions and Payments</h2>
      <p>
        Masari may offer optional paid features or subscriptions. Pricing,
        billing cycles, and feature availability will be disclosed within the
        app.
      </p>
      <p>
        Subscriptions automatically renew unless canceled through your platform
        provider (e.g., Apple App Store or Google Play). Refunds and billing
        issues are handled according to the policies of the platform through
        which the purchase was made.
      </p>

      <h2>9. Beta Disclaimer</h2>
      <p>
        Masari is currently offered in beta. Features may change, errors may
        occur, and service interruptions may happen without notice.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may stop using Masari at any time. We may suspend or terminate
        access if these Terms are violated or if required for security or legal
        reasons.
      </p>

      <h2>11. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Masari is provided “as is”
        without warranties of any kind. We are not liable for financial losses,
        data loss, or damages arising from use of the service.
      </p>

      <h2>12. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of Masari
        after changes become effective constitutes acceptance of the updated
        Terms.
      </p>

      <h2>13. Governing Law</h2>
      <p>
        These Terms are governed by applicable laws in the jurisdiction where
        the service operator is established, unless otherwise required by
        consumer protection laws.
      </p>

      <h2>14. Contact</h2>
      <p>For questions, contact: masari@salahslab.com</p>
    </main>
  );
}
