export default function Terms() {
  return (
    <main className="policy-page">
      <h1>Terms and Conditions</h1>
      <p>
        <strong>Last Updated: April 30, 2025</strong>
      </p>

      <p>
        Masari is a cloud-based personal finance application operated by Salah's
        Lab (Tokyo, Japan) that enables users to track expenses, organize
        financial information, and receive AI-powered insights. By accessing or
        using Masari, you agree to these Terms and Conditions. If you do not
        agree, do not use the service.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 13 years old (or the minimum legal age in your
        jurisdiction) to use Masari. By using Masari, you confirm that you meet
        this requirement.
      </p>

      <h2>2. Use of Service</h2>
      <p>You agree to:</p>
      <ul>
        <li>Use Masari only for lawful personal purposes</li>
        <li>Provide accurate information where applicable</li>
        <li>
          Not attempt to disrupt, reverse engineer, decompile, or misuse the
          service or its underlying systems
        </li>
        <li>
          Not use Masari to store or transmit unlawful, harmful, or fraudulent
          content
        </li>
      </ul>

      <h2>3. Accounts</h2>
      <p>
        You are responsible for maintaining the security of your account and for
        all activity that occurs under it. Masari uses email-based one-time
        passcodes (OTP) for authentication — we do not store passwords. You
        should use an email address you control and keep access to it. One
        account per user is expected; creating multiple accounts to circumvent
        limitations is not permitted. If you suspect unauthorized access to your
        account, contact us immediately at{" "}
        <a href="mailto:masari@salahslab.com">masari@salahslab.com</a>.
      </p>

      <h2>4. Intellectual Property</h2>
      <p>
        Masari and all of its content, features, design, code, and branding are
        owned by Salah's Lab and protected by applicable intellectual property
        laws. You are granted a limited, non-exclusive, non-transferable,
        revocable license to use Masari on your personal device solely for
        personal, non-commercial purposes in accordance with these Terms.
        Nothing in these Terms transfers any ownership rights to you.
      </p>

      <h2>5. Your Data</h2>
      <p>
        You retain full ownership of the financial and personal data you enter
        into Masari. By using the service, you grant Salah's Lab a limited
        license to process your data solely to provide the features you request
        — including AI-powered insights, synchronization, and notifications. We
        do not use your financial data for advertising, analytics profiling, or
        any purpose beyond delivering the service to you. For full details on
        how your data is handled, see our <a href="/privacy">Privacy Policy</a>.
      </p>

      <h2>6. Cloud-Based Service</h2>
      <p>
        Masari requires an internet connection to function. We do not guarantee
        uninterrupted availability. Scheduled maintenance, infrastructure
        issues, or third-party service outages may temporarily affect access. We
        will make reasonable efforts to minimize disruption.
      </p>

      <h2>7. Financial Disclaimer</h2>
      <p>
        Masari is a budgeting and expense tracking tool only. It does not
        provide financial, investment, tax, or legal advice. Any insights,
        summaries, or suggestions generated by the app — including those
        produced by AI — are informational only and should not be relied upon as
        professional advice. Always consult a qualified professional for
        financial decisions.
      </p>

      <h2>8. AI Features</h2>
      <p>
        Masari includes AI-powered features that process your financial data to
        generate insights and automation. These outputs may be incomplete,
        inaccurate, or not suited to your specific situation. You remain
        responsible for reviewing and verifying all financial information. AI
        features are provided for convenience only and do not constitute
        professional advice of any kind.
      </p>

      <h2>9. Subscriptions and Payments</h2>
      <p>
        Masari may offer optional paid features or subscriptions. Pricing,
        billing cycles, and included features will be clearly disclosed within
        the app before purchase.
      </p>
      <p>
        Subscriptions are managed through the Apple App Store and automatically
        renew unless canceled at least 24 hours before the end of the current
        billing period. To cancel, go to your App Store account settings.
        Refunds and billing disputes are handled in accordance with Apple's
        standard policies.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may stop using Masari at any time. You may request account deletion
        by contacting{" "}
        <a href="mailto:masari@salahslab.com">masari@salahslab.com</a>. Upon
        termination, your personal data will be deleted or anonymized within 90
        days in accordance with our <a href="/privacy">Privacy Policy</a>.
      </p>
      <p>
        Salah's Lab may suspend or terminate your access if you violate these
        Terms, or if required for security, legal, or operational reasons. In
        such cases, we will make reasonable efforts to notify you unless
        prohibited by law.
      </p>

      <h2>11. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, Masari is provided
        "as is" and "as available" without warranties of any kind, express or
        implied, including but not limited to warranties of merchantability,
        fitness for a particular purpose, or uninterrupted availability. Salah's
        Lab is not liable for any financial losses, data loss, indirect,
        incidental, or consequential damages arising from your use of or
        inability to use the service.
      </p>

      <h2>12. Severability</h2>
      <p>
        If any provision of these Terms is found to be invalid or unenforceable
        under applicable law, that provision will be modified to the minimum
        extent necessary to make it enforceable, or severed if modification is
        not possible. The remaining provisions will continue in full force and
        effect.
      </p>

      <h2>13. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. For material changes, we
        will notify you via email or in-app notice before the change takes
        effect. The "Last Updated" date at the top of this page will always
        reflect the most recent revision. Continued use of Masari after the
        effective date constitutes acceptance of the updated Terms.
      </p>

      <h2>14. Governing Law and Disputes</h2>
      <p>
        These Terms are governed by and construed in accordance with the laws of
        Japan. Any disputes arising out of or in connection with these Terms
        shall be subject to the exclusive jurisdiction of the courts of Tokyo,
        Japan, unless otherwise required by mandatory consumer protection laws
        in your jurisdiction.
      </p>

      <h2>15. Contact</h2>
      <p>
        For questions or concerns about these Terms:
        <br />
        <a href="mailto:masari@salahslab.com">masari@salahslab.com</a>
        <br />
        Salah's Lab — Tokyo, Japan
      </p>
    </main>
  );
}
